### ISSUE TITLE
enchanted books

### ISSUE THREAD

**Issue by vaniron** [michael1011/BackPacks#19]
Enchanted books are loosing their enchant upon taking from backpacks.. can this be fixed?

**Comment by michael1011** [comment]
What Minecraft and plugin version are you using? @aglarcz

**Comment by vaniron** [comment]
latest spigot 1.10.2 with backpacks 2.2.0 from spigotmc.org site

**Comment by michael1011** [comment]
Fixed! You can get the build [here](https://michael1011.at/jenkins/job/BackPacks/154/artifact/build/libs/BackPacks-2.2.1.jar). 
Please tell me if it works.
