### ISSUE TITLE
Item Bug in FurnaceBackPack

### ISSUE THREAD

**Issue by H4nSolo** [michael1011/BackPacks#20]
When you have a FurnaceBackPack, you can select a stack Coal without placing that on the Coal Slot. Then when you change the Stack into another block / item and fastclick on the coal slot of the FurnaceBackPack, somtime the placed the different stack in the slot. When you close the BackPack and reopened it, in the slot for coal he replaced the different block / stack into Coal.

No Errors in the Game Console or Logs. 
This Bug ist proofed on latest build #154.

**Comment by michael1011** [comment]
Which Minecraft version?

**Comment by H4nSolo** [comment]
CraftBukkit version git-Spigot-2038f4a-cd36f6f (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

**Comment by michael1011** [comment]
Fixed with [this commit](https://github.com/michael1011/BackPacks/commit/9909deef601422876d9c222d5682e204cd02d17e). Get the build [here](https://michael1011.at/jenkins/job/BackPacks/155/artifact/build/libs/BackPacks-2.2.1.jar).
Tell me if you have any other issues :)
