### ISSUE TITLE
Backpack is copying items

### ISSUE THREAD

**Issue by kamziksvk** [michael1011/BackPacks#21]
Hello, I have find out a serious Issue in your plugin. When you have a Big or Small Backpack crafted, and you do rightclick on the another chest filled with items, it works like a copy machine. It copies all the items in that chest into the Backpack. This is a serious issue and I am not sure how to fix it. Can you please take a look at it? 

Including video demonstration: https://www.youtube.com/watch?v=Ls9QVGzn-VQ&feature=youtu.be

Edit: SQL DB is configured, I erased it for forum purposes...

Code of config:

> # BackPacks 2.2.1
> # By michael1011
> #
> 
> # Don't touch this variable! It would destroy your config files!
> configVersion: 2
> 
> # Setup your MySQL connection here
> MySQL:

> 
> 
> # If a player dies with a backpack in his inventory should the content of backpack get dropped too?
> dropOnDeath: true
> 
> # Should players be able to store backpacks in backpacks?
> BackPackInBackPack: false
> 
> 
> # the updater will search for updates here: http://bit.ly/2cXN1dD
> # and it will only use versions with the type 'release'
> Updater:
>   enabled: true
> 
>   # in whole hours
>   interval: 24
> 
>   # if this is true the plugin will download the latest version and reload the server after the download automatically
>   # if it's false it will send every player with the permission 'backpacks.update' a message that a new version is available on join
>   autoUpdate: false
> 
> 
> # Delete the defaults and create your own backpacks here
> # You can create backpacks with the /bpcreate command too
> # Find all materials here: http://bit.ly/21vbetj
> 
> # Important: every description must be unique!
> BackPacks:
>   # List all BackPacks that should be enabled
>   enabled:
>     1: "MalyBatoh"
>     2: "VelkyBatoh"
>     3: "PrenosnaPec"
> 
>   MalyBatoh:
>     name: "&3Maly Batoh"
>     type: "normal"
> 
>     # Important: every description must be unique!
>     description:
>       1: "&7Malicky batoh na plecia"                                
>       2: "&7ktory dokaze uniest zakladne vybavenie."
>       3: "&cOtvorit kliknutim pravym tlacitkom."
> 
>     # Must be divisible by 9
>     slots: 9
> 
>     material: "CHEST"
> 
>     crafting:
>       1: "A+A+A"
>       2: "A+B+A"
>       3: "A+A+A"
> 
>       materials:
>         A: "GOLD_INGOT"
>         B: "CHEST"
> 
>   VelkyBatoh:
>     name: "&2Batoh"
>     type: "normal"
> 
>     description:
>       1: "&7Pohodlny batoh na plecia"
>       2: "&7skryvajuci vela ulozneho priestoru."
>       3: "&cOtvorit kliknutim pravym tlacitkom."
> 
>     slots: 27
> 
>     material: "ENDER_CHEST"
> 
>     crafting:
>       1: "D+D+D"
>       2: "D+E+D"
>       3: "D+D+D"
> 
>       materials:
>         D: "WHEAT"
>         E: "CHEST"
> 
>  
>   PrenosnaPec:
>     name: "&4Prenosna piecka"
>     type: "furnace"
> 
>     description:
>       1: "&7Mala prenosna autopiecka"
>       2: "&7vhodna na opecenie jedla."
>       2: "&cOtvorit kliknutim pravym tlacitkom."
> 
>     gui:
>       enabled: true
> 
>     material: "FURNACE"
> 
>     crafting:
>       1: "C+B+C"
>       2: "B+F+B"
>       3: "C+B+C"
> 
>       materials:
>         C: "COAL"
>         B: "COAL_BLOCK"
>         F: "FURNACE"

**Comment by MrJuju0319** [comment]
Chang your mysql password now

**Comment by kamziksvk** [comment]
Already changed...  My mistake :)

Dňa 13. 12. 2016 12:59 používateľ "MrJuju0319" <notifications@github.com>
napísal:

**Comment by MrJuju0319** [comment]
Yes is good :)

**Comment by kamziksvk** [comment]
Do you think you can help me with this problem? I think that is not the
config bug but the plugin, but unfortunately i am not a scripter :)

Dňa 13. 12. 2016 13:37 používateľ "MrJuju0319" <notifications@github.com>
napísal:

> Yes is good :)
>

**Comment by MrJuju0319** [comment]
I Don't help you, is in the code.
Sorry

**Comment by kamziksvk** [comment]
Ok thank you :) I hope the author will find out :)

**Comment by michael1011** [comment]
Already answered [on Spigot](https://www.spigotmc.org/threads/backpacks.130659/page-5). I will try to fix it.
