### ISSUE TITLE
BackPack Database Problem

### ISSUE THREAD

**Issue by H4nSolo** [michael1011/BackPacks#25]
If the update to 2.3.0 some players complain to me that the contents of the 2.2.1 / 2.2.2, which was previously placed in the BackPack, are no longer displayed in the 2.3.0. My suspicion is that he overwrites the backpacks of content by a new blank BP when I give them a new one.

**Comment by michael1011** [comment]
Should be fixed in 7b570dd72fcb5ed6865dfa95298d2338385e54a1
