### ISSUE TITLE
How to give permissions?

### ISSUE THREAD

**Issue by sewer159** [michael1011/BackPacks#26]
How to give permission to other people? On the server after installing the plugin nobody but me does not have permission to open the backpack (they can craft it).

**Comment by michael1011** [comment]
The permission to open a BackPack is **backpacks.use.\<name of the BackPack>**

**Comment by sewer159** [comment]
Where can I find it?
Should I write in this into "permission.yml" file of server files?

**Comment by michael1011** [comment]
If you want to know how to give a player a permission you just have to google it. (The most used permissions plugin is [PermissionsEx](https://dev.bukkit.org/projects/permissionsex))

**Comment by sewer159** [comment]
I see. I didn't know that i must have permission plugin. Thank You.
