### ISSUE TITLE
Several small or large backpacks

### ISSUE THREAD

**Issue by H4nSolo** [michael1011/BackPacks#3]
At the moment you can have only one of little or big Backpack,
but is it possible to add more then one with different Contents?

For Example:

One little Backpack with Tools
One little Backpack with Ores or other Blocks
etc...

thx

**Comment by michael1011** [comment]
In the new version (2.0.0) will be something _like_ this. You can create as many BackPacks as you want **in the config**. They need different crafting recipes and different names and all players with the permission will be able to craft them.

Take a look at the new config file here: https://github.com/michael1011/BackPacks/blob/master/src/main/resources/config.yml
