### ISSUE TITLE
Players Owned BackPack Name?

### ISSUE THREAD

**Issue by H4nSolo** [michael1011/BackPacks#4]
Some Player ask me for changing her Backpacks name.
Is that possible to change the name with a Amboss?

**Comment by michael1011** [comment]
Not _yet_. The backpack is identified by the name and the lore (description). If it its not possible to change the lore ingame I will add a option to the config.

**Comment by michael1011** [comment]
**Fixed** 
Download [Build #19](https://michael1011.at/jenkins/job/BackPacks/19/) or above, delete the old config.yml file, restart your server and check the config. There should be the option _identifyOnlyByLore_ enable it and it will work.

![2016-08-29_22 23 15](https://cloud.githubusercontent.com/assets/8138838/18066413/a6de0096-6e38-11e6-8c6b-b7a367d5a9c2.png)
![2016-08-29_22 23 27](https://cloud.githubusercontent.com/assets/8138838/18066415/a9643b14-6e38-11e6-9f26-6e5f4fec9585.png)
